[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "20"

[build]
  publish = ".histoire/dist"
  command = "npx pnpm@latest i --store=node_modules/.pnpm-store && npx pnpm@latest run story:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"